name: ci

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🧳Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🛠Build
        run: |
          yarn install
          yarn build

      - name: 🚀Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
